# Site settings
title: dan.carley.co
email: dan.carley+hello@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dan.carley.co" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title/

twitter_username: dancarley
github_username:  dcarley
disqus_short_name: dancarley

# Build settings
markdown: kramdown
