baseURL: http://dan.carley.co
languageCode: en-us
title: dan.carley.co
theme: minimo
permalinks:
  post: /blog/:year/:month/:day/:title/
menu:
  main:
    - name: "about"
      identifier: "about"
      url: "/about/"
