baseURL: http://dan.carley.co
languageCode: en-us
title: dan.carley.co
theme: minimo
pygmentsCodeFences: true
permalinks:
  post: /blog/:year/:month/:day/:title/
menu:
  main:
    - name: "home"
      identifier: "home"
      url: "/"
      weight: 1
    - name: "about"
      identifier: "about"
      url: "/about/"
      weight: 2
