version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    environment:
      HUGO_VERSION: 0.40.2
    steps:
      - checkout
      - run: git submodule update --init
      - run: mkdir -p bin
      - run: curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar -zxvC bin hugo
      - run: ./bin/hugo -v
      - persist_to_workspace:
          root: ~/project
          paths:
            - public

  deploy:
    docker:
      - image: circleci/golang:1.10
    environment:
      S3DEPLOY_VERSION: 2.0.2
      BUCKET_NAME: dan.carley.co
    steps:
      - attach_workspace:
          at: ~/project
      - run: mkdir -p bin
      - run: curl -L https://github.com/bep/s3deploy/releases/download/v${S3DEPLOY_VERSION}/s3deploy_${S3DEPLOY_VERSION}_Linux-64bit.tar.gz | tar -zxvC bin s3deploy
      - run: ./bin/s3deploy -source=public/ -region=eu-west-1 -bucket=${BUCKET_NAME}

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
