version = 1

[install]
hugo.pkg-path = "hugo"
hugo.version = "0.87.0"
hugo.pkg-group = "hugo"
rclone.pkg-path = "rclone"

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
